import connectDB from "@/lib/db";
import Product from "@/models/Product";
import { NextResponse } from "next/server";

export async function GET() {
    await connectDB();

    await Product.deleteMany();

    await Product.insertMany([
        { title: "Blue Denim Jacket", price: 59.99, category: "Clothing", image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400&q=80", description: "A timeless blue denim jacket crafted from heavyweight cotton fabric, perfect for layering on casual outings or weekend trips. Features classic button-front closure, chest pockets, and a relaxed fit that pairs with anything." },
        { title: "Running Sneakers", price: 89.99, category: "Footwear", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80", description: "Engineered for performance, these lightweight running sneakers feature responsive cushioning and a breathable mesh upper to keep your feet cool during long runs. The durable rubber outsole provides excellent grip on all surfaces." },
        { title: "Wireless Headphones", price: 129.99, category: "Electronics", image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80", description: "Experience crystal-clear audio with these premium over-ear headphones featuring active noise cancellation and an impressive 30-hour battery life. Bluetooth 5.0 ensures a stable connection up to 10 meters away." },
        { title: "Leather Wallet", price: 34.99, category: "Accessories", image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&q=80", description: "Handcrafted from genuine full-grain leather, this slim bifold wallet holds up to 8 cards and features built-in RFID-blocking technology to protect your personal data. Ages beautifully with everyday use." },
        { title: "Stainless Steel Water Bottle", price: 24.99, category: "Kitchen", image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80", description: "This double-wall insulated 500ml stainless steel bottle keeps drinks cold for 24 hours and hot for 12 hours. The leak-proof lid and scratch-resistant exterior make it ideal for gym, hiking, or daily commutes." },
        { title: "Yoga Mat", price: 44.99, category: "Sports", image: "https://images.unsplash.com/photo-1601925228008-34b2bc8a1c4b?w=400&q=80", description: "Made from eco-friendly natural rubber, this 6mm thick yoga mat delivers superior grip and cushioning for all types of yoga and floor exercises. Includes a carrying strap and is easy to wipe clean after every session." },
        { title: "Sunglasses", price: 19.99, category: "Accessories", image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&q=80", description: "These stylish UV400 polarized sunglasses eliminate glare and protect your eyes from harmful rays in a lightweight, durable frame. A versatile unisex design that suits both casual wear and outdoor activities." },
        { title: "Mechanical Keyboard", price: 109.99, category: "Electronics", image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&q=80", description: "A compact tenkeyless mechanical keyboard with tactile switches and per-key RGB backlighting, built for gamers and typists who demand speed and precision. The aluminium base adds durability and a premium feel on your desk." },
        { title: "Cotton T-Shirt", price: 14.99, category: "Clothing", image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80", description: "Softer with every wash, this classic crew-neck t-shirt is made from 100% GOTS-certified organic cotton that's gentle on skin and the environment. Available in a range of colors with a regular fit that works for any occasion." },
        { title: "Backpack", price: 49.99, category: "Bags", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80", description: "This rugged 30L backpack features a padded 15-inch laptop compartment, multiple organizer pockets, and a built-in USB charging port so you stay powered on the go. Water-resistant nylon fabric protects your gear in any weather." },
        { title: "Smart Watch", price: 199.99, category: "Electronics", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80", description: "A feature-packed smartwatch with heart rate monitoring, sleep tracking, GPS, and 7-day battery life. Syncs with iOS and Android to show notifications, calls, and fitness stats right on your wrist." },
        { title: "Hoodie Sweatshirt", price: 49.99, category: "Clothing", image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80", description: "A cozy pullover hoodie made from a soft cotton-polyester blend with a kangaroo pocket and adjustable drawstring hood. Perfect for lounging at home, morning jogs, or casual everyday wear in cooler weather." },
        { title: "Wireless Mouse", price: 39.99, category: "Electronics", image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80", description: "An ergonomic wireless mouse with a 2.4GHz USB receiver, adjustable DPI up to 1600, and a silent click design for distraction-free work. Compatible with Windows, Mac, and Linux." },
        { title: "Hiking Boots", price: 119.99, category: "Footwear", image: "https://images.unsplash.com/photo-1520219306100-ec4afba9d4c8?w=400&q=80", description: "Waterproof mid-cut hiking boots with a rugged Vibram outsole for maximum traction on rocky trails. The cushioned ankle support and breathable Gore-Tex lining keep your feet comfortable on long mountain hikes." },
        { title: "Resistance Bands Set", price: 22.99, category: "Sports", image: "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400&q=80", description: "A set of 5 latex resistance bands with varying tension levels for full-body strength training at home or the gym. Includes a carry bag and exercise guide for beginners and advanced users." },
        { title: "Portable Bluetooth Speaker", price: 59.99, category: "Electronics", image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&q=80", description: "A waterproof IPX7 portable speaker delivering 360-degree rich bass sound with 12 hours of playtime on a single charge. Compact enough to fit in a backpack, perfect for outdoor trips and beach days." },
        { title: "Slim Fit Chinos", price: 44.99, category: "Clothing", image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80", description: "Versatile slim-fit chino trousers crafted from stretch cotton for all-day comfort and a clean, polished look. Suitable for both office wear and casual outings, available in multiple neutral tones." },
        { title: "Travel Duffel Bag", price: 64.99, category: "Bags", image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80", description: "A spacious 40L duffel bag with a separate shoe compartment, adjustable shoulder strap, and multiple zip pockets for organized packing. Made from tear-resistant polyester, ideal for weekend trips and gym sessions." },
        { title: "Ceramic Coffee Mug", price: 16.99, category: "Kitchen", image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&q=80", description: "A large 400ml ceramic coffee mug with a comfortable C-handle and minimalist design, microwave and dishwasher safe. The perfect companion for your morning coffee, tea, or hot cocoa." },
        { title: "Leather Belt", price: 27.99, category: "Accessories", image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=400&q=80", description: "A classic full-grain leather belt with a polished silver buckle, available in black and brown. A timeless wardrobe essential for formal and casual outfits." },
        { title: "Wireless Earbuds", price: 79.99, category: "Electronics", image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&q=80", description: "True wireless earbuds with active noise cancellation, 6-hour playback plus 18 hours with the charging case, and an IPX4 sweat-resistant rating. Includes multiple ear tip sizes for a secure, comfortable fit." },
        { title: "Sports Water Bottle", price: 18.99, category: "Sports", image: "https://images.unsplash.com/photo-1625708458528-802ec79b1ed8?w=400&q=80", description: "A lightweight 750ml BPA-free sports bottle with a flip-top straw lid and easy carry loop. Ideal for cycling, running, or hitting the gym, fits standard bottle cages on bikes." },
        { title: "Laptop Stand", price: 34.99, category: "Electronics", image: "https://images.unsplash.com/photo-1611186871525-f1e46de3d3e0?w=400&q=80", description: "An adjustable aluminium laptop stand with six height settings, improving posture and airflow for cooler performance. Folds flat for portability and supports laptops from 10 to 17 inches." },
        { title: "Canvas Tote Bag", price: 14.99, category: "Bags", image: "https://images.unsplash.com/photo-1594938298603-c8148c4b4357?w=400&q=80", description: "A sturdy reusable canvas tote bag with long handles and a large main compartment, perfect for grocery shopping, beach trips, or everyday errands. Eco-friendly alternative to single-use plastic bags." },
        { title: "Jump Rope", price: 12.99, category: "Sports", image: "https://images.unsplash.com/photo-1598632640487-6ea4a4e8b963?w=400&q=80", description: "A speed jump rope with ball-bearing handles for smooth, tangle-free rotation, suitable for cardio workouts, boxing training, and HIIT. The adjustable cable fits all heights." },
        { title: "Slim Laptop Bag", price: 42.99, category: "Bags", image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80", description: "A professional slim shoulder bag designed to fit 15.6-inch laptops with a padded compartment, front organizer pocket for accessories, and a luggage pass-through strap for easy airport travel." },
        { title: "Scented Candle Set", price: 29.99, category: "Home", image: "https://images.unsplash.com/photo-1603905756291-730935dee3d5?w=400&q=80", description: "A set of three hand-poured soy wax candles in calming lavender, warm vanilla, and fresh eucalyptus scents, each with a 40-hour burn time. Beautifully packaged, makes a perfect gift for any occasion." },
        { title: "Phone Stand", price: 15.99, category: "Electronics", image: "https://images.unsplash.com/photo-1586495777744-4e6232bf2263?w=400&q=80", description: "An adjustable aluminium phone stand with a 360-degree rotating base for portrait and landscape viewing, compatible with all smartphones and small tablets. Great for video calls, watching content, or desk use." },
        { title: "Running Shorts", price: 29.99, category: "Sports", image: "https://images.unsplash.com/photo-1562183241-b937e95585b6?w=400&q=80", description: "Lightweight 5-inch running shorts made from quick-dry fabric with a built-in liner, zip pocket for your phone or keys, and a reflective strip for low-light visibility. Designed for speed and comfort." },
        { title: "Desk Lamp", price: 38.99, category: "Home", image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&q=80", description: "An LED desk lamp with 5 color temperatures, 10 brightness levels, a USB charging port, and a flexible gooseneck arm. Eye-care technology reduces flicker and blue light for comfortable long work or study sessions." },
        { title: "Foam Roller", price: 25.99, category: "Sports", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80", description: "A high-density EVA foam roller for deep tissue muscle massage and post-workout recovery, helping relieve soreness and improve flexibility. The textured surface targets tight muscles in the back, legs, and calves." },
    ]);

    return NextResponse.json({ message: "Database seeded successfully with 30 products." });
}
